spring.application.name=hospitalmanagementsystem
server.port=8081

spring.datasource.url= jdbc:postgresql:       //localhost:5432/hospitalmanagementsystem
spring.datasource.username=postgres           // This Your Postgresql Username
spring.datasource.password=password           // This Your Postgresql Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
